dist: xenial

language: go
go:
  - "1.12.x"

cache:
  directories:
    - $GOPATH/pkg/mod

git:
  depth: 1

branches:
  only:
  - master

env:
  - GO111MODULE=on

# In the Travis VM-based build environment, IPv6 networking is not
# enabled by default. The sysctl operations below enable IPv6.
# IPv6 is needed by some of the CoreDNS test cases.

before_install:
  - cat /proc/net/if_inet6
  - uname -a
  - sudo bash -c 'if [ `cat /proc/net/if_inet6 | wc -l` = "0" ]; then echo "Enabling IPv6" ; sysctl net.ipv6.conf.all.disable_ipv6=0 ; sysctl net.ipv6.conf.default.disable_ipv6=0 ; sysctl net.ipv6.conf.lo.disable_ipv6=0 ; fi'
  - cat /proc/net/if_inet6
  - env

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
  - cd ../../ && mkdir coredns
  - git clone --depth=1 --branch=master https://github.com/coredns/coredns.git coredns/coredns
  - cd coredns/coredns
  - sed -i '/^on:.*/i firewall:github.com/ihac/firewall/firewall' plugin.cfg
  - make


after_success:
  - bash <(curl -s https://codecov.io/bash)